/* generated by tools/build_elf_page.py - do not edit */
window.PAYLOAD_TILES = [
    { title: "etaHEN", description: "Homebrew enabler and payload host.", name: "etaHEN.elf", key: "etahen" },
    { title: "ps5-kstuff", description: "Kernel support payload and FPKG enabler.", name: "kstuff.elf", key: "kstuff" },
    { title: "ftpsrv", description: "FTP server. Runs on port 2121.", name: "ftpsrv-ps5.elf", key: "ftp" },
    { title: "klogsrv", description: "Kernel log server. Runs on port 3232.", name: "klogsrv-ps5.elf", key: "klog" },
    { title: "websrv", description: "Homebrew web server. Runs on port 8080.", name: "websrv-ps5.elf", key: "web" }
];
window.PAYLOAD_ART = { dir: "ui/", pfx: "btn-", on: true };
